print("DANNY")
print("Hello World")
print("Farewell")
print('dog')
print('cat')
print('I dont want to save this line')
print('I dont want to save this line')
print('I dont want to save this line')
print('I dont want to save this line')
print('I dont want to save this line')